// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv-L58pNcqSvefkTQG_Ebq0Pu1az1SwP8',
    appId: '1:830337340563:web:f0be2847103ffd681e2966',
    messagingSenderId: '830337340563',
    projectId: 'ebook-20dcb',
    authDomain: 'ebook-20dcb.firebaseapp.com',
    storageBucket: 'ebook-20dcb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCclEzS-1ZPFAbSfDpTNRQgDRcyBajFF1c',
    appId: '1:830337340563:android:f16b4eb41637ed541e2966',
    messagingSenderId: '830337340563',
    projectId: 'ebook-20dcb',
    storageBucket: 'ebook-20dcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiupj1IHxthE64026N1JYSGZCsCwIZfO8',
    appId: '1:830337340563:ios:b0bceacce1e351dc1e2966',
    messagingSenderId: '830337340563',
    projectId: 'ebook-20dcb',
    storageBucket: 'ebook-20dcb.appspot.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiupj1IHxthE64026N1JYSGZCsCwIZfO8',
    appId: '1:830337340563:ios:dcbaf796c07c96f21e2966',
    messagingSenderId: '830337340563',
    projectId: 'ebook-20dcb',
    storageBucket: 'ebook-20dcb.appspot.com',
    iosBundleId: 'com.example.eBook.RunnerTests',
  );
}
